project_id = "wgjmhlzpymcujqlrptoo"

[functions.ai-help]
verify_jwt = false

[functions.process-voice]
verify_jwt = false

[functions.voice-transcribe]
verify_jwt = false

[functions.voice-chat]
verify_jwt = false
